workflows:
  android-free-workflow:
    name: Linkie-MO Android Build (Free)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - signing_credentials 
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android APK (File cài đặt trực tiếp)
        script: |
          flutter build apk --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - tahieunhann@gmail.com
